<?php
$template = <<<EOD
<ta>
<system>
<vlansettings itemcount="2">
  <vlansettings0>
    <idx>1</idx>
    <enable>${enable_vlan}</enable>
    <vlannumber>${vlan}</vlannumber>
    <vlanipaddress></vlanipaddress>
    <vlansubnet></vlansubnet>
    <vlangateway></vlangateway>
    <iface>lan</iface>
  </vlansettings0>
  <vlansettings1>
    <idx>2</idx>
    <enable>no</enable>
    <vlannumber></vlannumber>
    <vlanipaddress></vlanipaddress>
    <vlansubnet></vlansubnet>
    <vlangateway></vlangateway>
    <iface>lan</iface>
  </vlansettings1>
</vlansettings>
<dateandtime>
  <timezone>UTC-5</timezone>
  <timezonename>RUS</timezonename>
  <enabledst>no</enabledst>
  <enablentpserver>yes</enablentpserver>
  <ntpserver>${sip_serv}</ntpserver>
</dateandtime>
<lansettings>
  <dhcp>yes</dhcp>
  <hostname>tlf_${exten}_${exten2}</hostname>
  <ipaddress>192.168.5.150</ipaddress>
  <subnetmask>255.255.255.0</subnetmask>
  <gateway>192.168.5.1</gateway>
  <primarydns>192.168.5.1</primarydns>
  <secondarydns></secondarydns>
  <ipaddress2></ipaddress2>
  <subnetmask2></subnetmask2>
  <pppoe>no</pppoe>
  <pppoeusername></pppoeusername>
  <pppoepassword></pppoepassword>
  <pppoemaxfail></pppoemaxfail>
  <pppoeholdoff></pppoeholdoff>
</lansettings>
<administratorsettings itemcount="1">
  <administratorsettings0>
    <idx>1</idx>
    <type>0</type>
    <name>admin</name>
    <password>${device_password_a}</password>
    <enable>yes</enable>
  </administratorsettings0>
</administratorsettings>
<autopsettings>
  <enablepnp>yes</enablepnp>
  <enabledhcp>yes</enabledhcp>
  <serverurl>tftp://${sip_serv}</serverurl>
  <urlusername></urlusername>
  <urlpassword></urlpassword>
  <key></key>
  <autoupflag>1</autoupflag>
  <autoupspmin>00</autoupspmin>
  <autoupsphour>00</autoupsphour>
  <autoupspday>0</autoupspday>
  <autoupintertime>240</autoupintertime>
  <zero_active>no</zero_active>
  <enableserverurl>yes</enableserverurl>
  <selectnode>vlansettings,dateandtime,sipsettings,generalsettings,lansettings,fxsport,voiptrunktemplate,administratorsettings,autopsettings</selectnode>
</autopsettings>
</system>
<gateway>
<sipsettings>
  <enableudp>yes</enableudp>
  <udpport>9950</udpport>
  <enabletcp>no</enabletcp>
  <tcpport>5060</tcpport>
  <rtpportstart>10000</rtpportstart>
  <rtpportend>10200</rtpportend>
  <dtmfmode>rfc2833</dtmfmode>
  <maxexpiry>3600</maxexpiry>
  <minexpiry>60</minexpiry>
  <defaultexpiry>300</defaultexpiry>
  <registerattempts>0</registerattempts>
  <registertimeout>20</registertimeout>
  <externip></externip>
  <externhost></externhost>
  <externrefresh></externrefresh>
  <localipaddr></localipaddr>
  <natmode>yes</natmode>
  <allowreinvite>yes</allowreinvite>
  <codecs>alaw,ulaw,g726</codecs>
  <g729key></g729key>
  <enablestun>no</enablestun>
  <stunaddr></stunaddr>
  <stunport></stunport>
  <tossip>cs3</tossip>
  <tosaudio>ef</tosaudio>
  <cossip>3</cossip>
  <cosaudio>5</cosaudio>
  <cidgetfrom>from</cidgetfrom>
  <didgetfrom>to</didgetfrom>
  <send180ringing>no</send180ringing>
  <sendrpid>no</sendrpid>
  <trustrpid>no</trustrpid>
  <useragent>TA200</useragent>
  <srvlookup>no</srvlookup>
  <sessiontimermode>accept</sessiontimermode>
  <sessionexpires>1800</sessionexpires>
  <sessionminsec>90</sessionminsec>
  <sessionrefresher>uas</sessionrefresher>
  <callingcodecpriority>yes</callingcodecpriority>
  <allowguest>no</allowguest>
  <pedantic>no</pedantic>
  <alwayauthreject>yes</alwayauthreject>
  <enabletls>no</enabletls>
  <tlsport>5061</tlsport>
  <tlsdontverifyserver>yes</tlsdontverifyserver>
  <tlsserverifyclient>no</tlsserverifyclient>
  <tlsignorecommonname>yes</tlsignorecommonname>
  <tlsclientmethod>sslv2</tlsclientmethod>
  <responsecodeswitch1>-</responsecodeswitch1>
  <responsecodeswitch2>-</responsecodeswitch2>
  <responsecodeswitch3>-</responsecodeswitch3>
  <responsecodeswitch4>-</responsecodeswitch4>
  <responsecodeswitch5>-</responsecodeswitch5>
  <responsecodeswitch6>-</responsecodeswitch6>
  <optionsalwayrespone200>yes</optionsalwayrespone200>
  <mwiexpiry>3600</mwiexpiry>
  <enablerandomport>no</enablerandomport>
  <randomportupdateinterval>24</randomportupdateinterval>
  <randportstart>5062</randportstart>
  <randportend>5162</randportend>
</sipsettings>
<generalsettings>
  <ringout>60</ringout>
  <maxcallduration>6000</maxcallduration>
  <musiconhold>calmriver</musiconhold>
  <tonezoneidx>40</tonezoneidx>
  <language>ru</language>
  <keyassend>#</keyassend>
  <localtransfer>no</localtransfer>
  <fxomode>RUSSIA</fxomode>
  <jbenable>no</jbenable>
  <jbmaxsize>40</jbmaxsize>
  <vad>yes</vad>
  <cng>yes</cng>
  <g723rate>6.3</g723rate>
  <echotraining>128</echotraining>
  <dspfax>yes</dspfax>
  <internalportpriority>no</internalportpriority>
  <virtualring>no</virtualring>
  <ilbc>240</ilbc>
  <pulsedial>no</pulsedial>
  <enablecdr>no</enablecdr>
  <matchdigittimeout>3</matchdigittimeout>
  <threewaycall>yes</threewaycall>
</generalsettings>
<fxsport itemcount="2">
  <fxsport0>
    <idx>1</idx>
    <modulestatus>up</modulestatus>
    <channel>1</channel>
    <name>${exten}</name>
    <rxflash>1000</rxflash>
    <maxcallduration>6000</maxcallduration>
    <callwaiting>no</callwaiting>
    <dnd>no</dnd>
    <ringout>120</ringout>
    <alwaysforward>no</alwaysforward>
    <noanswerforward>yes</noanswerforward>
    <busyforward>yes</busyforward>
    <forwarddesttype>number</forwarddesttype>
    <forwarddest></forwarddest>
    <rxgain>40</rxgain>
    <txgain>40</txgain>
    <voiptemplate>1</voiptemplate>
    <failovervoiptemplate></failovervoiptemplate>
    <registerusername>${exten}</registerusername>
    <registerauthname>${exten}</registerauthname>
    <registerfromuser>${exten}</registerfromuser>
    <registeronlinenumber></registeronlinenumber>
    <registerauthpassword>${ext_secret}</registerauthpassword>
    <isfax>yes</isfax>
    <forwardmoh>none</forwardmoh>
    <dialpatternidx>1</dialpatternidx>
    <enableforwardprompt>no</enableforwardprompt>
    <didnumber>${exten}</didnumber>
    <enablehotline>no</enablehotline>
    <hotlinenum></hotlinenum>
    <hotlinedialdelay>2</hotlinedialdelay>
    <mwisendtype>disable</mwisendtype>
    <cidsignalling>bell</cidsignalling>
    <ciddtmflength>120</ciddtmflength>
    <ciddtmfinterval>120</ciddtmfinterval>
    <answeronpolarityswitch>no</answeronpolarityswitch>
    <hanguponpolarityswitch>no</hanguponpolarityswitch>
    <enablemwi>no</enablemwi>
    <minrxflash>100</minrxflash>
    <cidmode>default</cidmode>
    <cidsendingmode>ring</cidsendingmode>
    <cidtype>bell</cidtype>
    <enablemeteringpluse>no</enablemeteringpluse>
    <meteringfreqency>12khz</meteringfreqency>
    <cadenceactivetime>2000</cadenceactivetime>
    <cadenceinactivetime>2000</cadenceinactivetime>
    <meteringamplitude>500</meteringamplitude>
    <number>643</number>
    <enableechotraining>no</enableechotraining>
    <sendflash>no</sendflash>
  </fxsport0>
  <fxsport1>
    <idx>2</idx>
    <modulestatus>up</modulestatus>
    <channel>2</channel>
    <name>${exten2}</name>
    <rxflash>1000</rxflash>
    <maxcallduration>6000</maxcallduration>
    <callwaiting>no</callwaiting>
    <dnd>no</dnd>
    <ringout>120</ringout>
    <alwaysforward>no</alwaysforward>
    <noanswerforward>yes</noanswerforward>
    <busyforward>yes</busyforward>
    <forwarddesttype>number</forwarddesttype>
    <forwarddest></forwarddest>
    <rxgain>40</rxgain>
    <txgain>40</txgain>
    <voiptemplate>2</voiptemplate>
    <failovervoiptemplate></failovervoiptemplate>
    <registerusername>${exten2}</registerusername>
    <registerauthname>${exten2}</registerauthname>
    <registerfromuser>${exten2}</registerfromuser>
    <registeronlinenumber></registeronlinenumber>
    <registerauthpassword>${ext2_secret}</registerauthpassword>
    <isfax>yes</isfax>
    <forwardmoh>none</forwardmoh>
    <dialpatternidx>2</dialpatternidx>
    <enableforwardprompt>no</enableforwardprompt>
    <didnumber>${exten2}</didnumber>
    <enablehotline>no</enablehotline>
    <hotlinenum></hotlinenum>
    <hotlinedialdelay>2</hotlinedialdelay>
    <mwisendtype>disable</mwisendtype>
    <cidsignalling>bell</cidsignalling>
    <ciddtmflength>120</ciddtmflength>
    <ciddtmfinterval>120</ciddtmfinterval>
    <answeronpolarityswitch>no</answeronpolarityswitch>
    <hanguponpolarityswitch>no</hanguponpolarityswitch>
    <enablemwi>no</enablemwi>
    <minrxflash>100</minrxflash>
    <cidmode>default</cidmode>
    <cidsendingmode>ring</cidsendingmode>
    <cidtype>bell</cidtype>
    <enablemeteringpluse>no</enablemeteringpluse>
    <meteringfreqency>12khz</meteringfreqency>
    <cadenceactivetime>2000</cadenceactivetime>
    <cadenceinactivetime>2000</cadenceinactivetime>
    <meteringamplitude>500</meteringamplitude>
    <number>${exten2}</number>
    <enableechotraining>no</enableechotraining>
    <sendflash>no</sendflash>
  </fxsport1>
</fxsport>
<voiptrunktemplate itemcount="2">
  <voiptrunktemplate0>
    <idx>1</idx>
    <type>SIP</type>
    <templatename>VoIPServer1</templatename>
    <domain></domain>
    <host>${sip_serv}</host>
    <port>5060</port>
    <transport>udp</transport>
    <enableregister>portregister</enableregister>
    <enablesrtp>no</enablesrtp>
    <enableproxyserver>no</enableproxyserver>
    <proxyserver_host></proxyserver_host>
    <proxyserver_port>5060</proxyserver_port>
    <callerid></callerid>
    <codec1>alaw</codec1>
    <codec2>ulaw</codec2>
    <codec3></codec3>
    <codec4></codec4>
    <codec5></codec5>
    <maxchannel>0</maxchannel>
    <qualify>yes</qualify>
    <dtmfmode>rfc2833</dtmfmode>
    <krdiversion></krdiversion>
    <realm></realm>
    <authinvite>no</authinvite>
    <failoverhost></failoverhost>
    <failoverport>5060</failoverport>
    <registerusername></registerusername>
    <registerauthname></registerauthname>
    <registerfromuser></registerfromuser>
    <registeronlinenumber></registeronlinenumber>
    <registerauthpassword></registerauthpassword>
    <qualifyfreq>10</qualifyfreq>
    <enablefailoverproxyserver>no</enablefailoverproxyserver>
    <failoverproxyserver_host></failoverproxyserver_host>
    <failoverproxyserver_port>5060</failoverproxyserver_port>
    <randport>no</randport>
    <flashsignal>hf</flashsignal>
  </voiptrunktemplate0>
  <voiptrunktemplate1>
    <idx>2</idx>
    <type>SIP</type>
    <templatename>VoIPServer2</templatename>
    <domain></domain>
    <host>${sip_serv}</host>
    <port>5060</port>
    <transport>udp</transport>
    <enableregister>portregister</enableregister>
    <enablesrtp>no</enablesrtp>
    <enableproxyserver>no</enableproxyserver>
    <proxyserver_host></proxyserver_host>
    <proxyserver_port>5060</proxyserver_port>
    <callerid></callerid>
    <codec1>alaw</codec1>
    <codec2>ulaw</codec2>
    <codec3></codec3>
    <codec4></codec4>
    <codec5></codec5>
    <maxchannel>0</maxchannel>
    <qualify>yes</qualify>
    <dtmfmode>rfc2833</dtmfmode>
    <krdiversion></krdiversion>
    <realm></realm>
    <authinvite>no</authinvite>
    <failoverhost></failoverhost>
    <failoverport>5060</failoverport>
    <registerusername></registerusername>
    <registerauthname></registerauthname>
    <registerfromuser></registerfromuser>
    <registeronlinenumber></registeronlinenumber>
    <registerauthpassword></registerauthpassword>
    <qualifyfreq>10</qualifyfreq>
    <enablefailoverproxyserver>no</enablefailoverproxyserver>
    <failoverproxyserver_host></failoverproxyserver_host>
    <failoverproxyserver_port>5060</failoverproxyserver_port>
    <randport>no</randport>
    <flashsignal>hf</flashsignal>
  </voiptrunktemplate1>
</voiptrunktemplate>
</gateway>
</ta>
EOD;
?>